# Creating DataFrames



In [1]:
import pandas as pd
import numpy as np

In [7]:
# Equi ( X , Y )
data = np.random.random(size=(5, 3))
print(data)

# Common 2D array and columns method
df = pd.DataFrame(data=data, columns=["A", "B", "C"])
df

[[0.5162056  0.97695706 0.45290438]
 [0.65980158 0.10910568 0.2808201 ]
 [0.51683904 0.98573522 0.20667211]
 [0.24298061 0.08008324 0.32743824]
 [0.48147558 0.37048609 0.9668116 ]]


A         B         C
0  0.516206  0.976957  0.452904
1  0.659802  0.109106  0.280820
2  0.516839  0.985735  0.206672
3  0.242981  0.080083  0.327438
4  0.481476  0.370486  0.966812

In [3]:
# A dictionary of columns
df = pd.DataFrame(data={"A": [1, 2, 3], "B": ["Sam", "Alex", "John"]})
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [14]:
# Or a list of rows (ie tuples) with a dtype
#                             (np.str, field limiter)
dtype = [("A", np.int), ("B", (np.str, 5))]
data = np.array([(1, "Sam"), (2, "Alex"), (3, "John")], dtype=dtype)
df = pd.DataFrame(data)
df

/tmp/ipykernel_4540/3946302628.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = [("A", np.int), ("B", (np.str, 3))]
/tmp/ipykernel_4540/3946302628.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = [("A", np.int

A    B
0  1  Sam
1  2  Ale
2  3  Joh

In [5]:
# Or the dictionary based version of list of rows
data = [{"A": 1, "B": "Sam"}, {"A": 2, "B": "Alex"}, {"A": 3, "B": "John"}]
df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John